export const FETCH_TODOS = 'FETCH_TODOS';

export const FETCH_TODOS_PENDING = 'FETCH_TODOS_PENDING';
export const FETCH_TODOS_FULFILLED = 'FETCH_TODOS_FULFILLED';
export const FETCH_TODOS_REJECTED = 'FETCH_TODOS_REJECTED';

export const CLEAR_TODOS = 'CLEAR_TODOS';
